.TH TRUEPRINT 1 "LOCAL" "ULTRIX 4.1"
.ad b
.SA 1
.SH NAME
trueprint - print program listings on postscript printer.
.SH SYNOPSIS
.B trueprint [ -HVbdDghlmnoOpPStwx24 ]
files
.SH DESCRIPTION
.I trueprint
is a general purpose program printing program.  It tries to produce everything
that anybody could need in a program printout without the need for large
numbers of switches or pipelines.
.I trueprint
can currently handle C, C++, Verilog, shell (including ksh),
perl, pascal, listing files and plain text files.
.PP
This man page is not the most complete source of documentation
for
.I trueprint.
The definitive documentation is in the info file.  You can
also use the --help option to trueprint for a quick summary of
options and other information.
.PP
Each page in the output has a default header consisting of the date or a
user-defined string, the current function name, and the overall page number
(which is used in the indexes); and a footer consisting of the date, the
current file name and page number within file, and the overall page number.
Each page can also have a string printed in large shaded
characters diagonally over the centre of each page - this could for example
give the version number or say "For your eyes only".
.PP
The printout has two function indexes at the front - one is an alphabetical
list of all functions and the other is a list of files with functions in
each file in alphabetical order.  The first is suppressed if there are no
functions and the second is suppressed if there is only one file.
.PP
If no language is specified on the command line then options are defaulted
to be appropriate for the first file specified on the command line.  The
filetype is taken from the suffix - valid suffixes are .c, .h, .cxx, .cpp, .hpp,
.v, .pas, .rep, .lst, .pl,
and .sh.  Any other suffix, or no suffix at all, is taken to be plain text.
.PP
The text of the printout has line numbers with
current brace depth (by default only for C and pascal) down the left hand
side.  Function names are in bold and comments are in italics.
.PP
It is possible to show differences between file versions, in which case
deleted lines are shown struck out with a minus sign in the extreme left-hand
margin, and added lines are shown in bold with a plus sign in the extreme
left-hand margin.
.PP
The shell variable $TP_OPTS can be set with parameters which will become
defaults; thus if TP_OPTS is set to "-p15" then the pointsize will default
to 15, but can be overriden on the command line.  This allows the user to
set up personal defaults.
.PP
.I trueprint
is under constant development, and any suggested enhancements should
be sent to enhance-trueprint@gnu.org.

.SH ARGUMENTS
.TP 15
.I filenames
The name of the files containing source code to be printed out.
.SH OPTIONS
Options can be used to customize just about every aspect of the
output.  Note that the list of options changes
over time and that this man page may get out of date - the latest list
is always available via the --help option.



.SH Miscellaneous options

.TP 15
.BI \-D " string" ", --debug=" string
set debug options to 
.I string

.TP 15
.BI \-O " string" ", --diff=" string
if
.I string
is a file then print diffs between
.I string
and input file otherwise use as a prefix and print diffs

.TP 15
.BI \-t " string" ", --language=" string
treat input as language.  Use --help languages for list.

.TP 15
.BI \-U " string" ", --username=" string
set username for coversheet

.TP 15
.B \-H, --help
Type help information

.TP 15
.BI "--help=" string
Type specific help information.  Use --help for a list of possible
strings.

.TP 15
.B \-V, --version
Type version information

.TP 15
.B \-N, --use-environment
use environment variables

.TP 15
.B \--N, --ignore-environment
don't use values from environment, such as time,
$USER, etc.  This is for test purposes, to make test results
more reproducible.


.SH Page furniture options

.TP 15
.BI \-X " string" ", --left-header=" string
Specify string for left side of header.

.TP 15
.BI \-x " string" ", --left-footer=" string
Specify string for left side of footer.

.TP 15
.BI \-Y " string" ", --center-header=" string
Specify string for center of header.

.TP 15
.BI \-y " string" ", --center-footer=" string
Specify string for center of footer.

.TP 15
.BI \-Z " string" ", --right-header=" string
Specify string for right side of header.

.TP 15
.BI \-z " string" ", --right-footer=" string
Specify string for right side of footer.

.TP 15
.BI \-m " string" ", --message=" string
Message to be printed over page.

.TP 15
.BI \-G " number" ", --gray-bands=" number
Emulate the old lineprinter paper with gray bands
across each page.  The value of number gives the width of
the bands and the gaps between them.

.TP 15
.B \-K, --headers
Include the header on each page.

.TP 15
.B \--K, --no-headers
Suppress the header on each page.

.TP 15
.B \-k, --footers
Include the footer on each page.

.TP 15
.B \--k, --no-footers
Suppress the footer on each page.

.TP 15
.B \-i, --no-braces-depth
Exclude the braces depth count.

.TP 15
.B \--i, --braces-depth
Include the braces depth count.

.TP 15
.B \-n, --no-line-numbers
Exclude the line number count.

.TP 15
.B \--n, --line-numbers
Include the line number count.


.SH Text formatting options

.TP 15
.B \-b, --no-page-break-after-function
Don't print page breaks at the end of functions.

.TP 15
.B \--b, --page-break-after-function
Print page breaks at the end of functions.

.TP 15
.B \-W, --no-intelligent-line-wrap
Wrap lines at exactly the line-wrap column.

.TP 15
.B \--W, --intelligent-line-wrap
Wrap lines intelligently at significant characters, such
as a space

.TP 15
.BI \-T " number" ", --tabsize=" number
Set tabsize (default 8).

.TP 15
.B \-E, --ignore-form-feeds
Don't expand form feed characters to new page.

.TP 15
.B \--E, --form-feeds
Expand form feed characters to new page.

.TP 15
.BI \-p " number" ", --point-size=" number
Specify point size (default 10).

.TP 15
.BI \-g " number" ", --leading=" number
Specify interline gap in points (default 1).

.TP 15
.BI \-w " number" ", --line-wrap=" number
Specify the line-wrap column.

.TP 15
.B --no-line-wrap
Turn off line-wrap.

.TP 15
.BI \-l " number" ", --page-length=" number
Specify number of lines on a page, point size is
calculated appropriately.


.SH Print selection options

.TP 15
.B \-C, --no-cover-sheet
Don't print cover sheet.

.TP 15
.B \--C, --cover-sheet
Print cover sheet.

.TP 15
.BI \-A " string" ", --print-pages=" string
Specify list of pages to be printed.

.TP 15
.B \-a, --no-prompt
Don't prompt for each page, whether it should be printed or not.

.TP 15
.B \--a, --prompt
Prompt for each page, whether it should be printed or not.

.TP 15
.B \-F, --no-file-index
Don't print file index.

.TP 15
.B \--F, --file-index
Print file index.

.TP 15
.B \-f, --no-function-index
Don't print function index.

.TP 15
.B \--f, --function-index
Print function index.

.TP 15
.B \-B, --no-print-body
Don't print body of text.

.TP 15
.B \--B, --print-body
Print body of text.


.SH Page format options

.TP 15
.B \-I, --no-holepunch
Don't leave space for holepunch at the side of each page.

.TP 15
.B \--I, --holepunch
Leave space for holepunch at the side of each page.

.TP 15
.B \-J, --no-top-holepunch
Don't leave space for holepunch at the top of each page.

.TP 15
.B \--J, --top-holepunch
Leave space for holepunch at the top of each page.

.TP 15
.B \-o p, --portrait
Print using portrait orientation.

.TP 15
.B \-o l, --landscape
Print using landscape orientation.

.TP 15
.B \-S 1, --single-sided
Print single-sided.

.TP 15
.B \-S 2, --double-sided
Print double-sided.

.TP 15
.B \-1, --one-up
Print 1-on-1 (default).

.TP 15
.B \-2, --two-up
Print 2-on-1.

.TP 15
.B \-3, --two-tall-up
Print 2-on-1 at 4-on-1 pointsize.

.TP 15
.B \-4, --four-up
Print 4-on-1.


.SH Output options

.TP 15
.BI \-d " string" ", --printer=" string
Use printer string.

.TP 15
.BI \-P " string" ", --printer=" string
Use printer string.

.TP 15
.BI \-s " string" ", --output=" string
Send output to filename string; use - for stdout.

.TP 15
.BI \-c " number" ", --copies=" number
Specify number of copies to be printed.

.TP 15

.SH STRING EXPANSION
Many options take a string that can contain sequences which will be
expanded as follows:
.IP %%
a percent character
.IP %m
month of year
.IP %d
day of month
.IP %y
year e.g. 1993
.IP %D
date mm/dd/yy
.IP %L
long date e.g. Fri Oct 8 11:49:51 1993
.IP %H
hour
.IP %M
minute
.IP %S
second
.IP %T
time HH:MM:SS
.IP %j
day of year ddd
.IP %w
day of week (Sunday = 0)
.IP %a
abbreviated weekday
.IP %h
abbreviated month
.IP %r
time in am/pm notation
.IP %p
page number in current file
.IP %P
overall page number
.IP %f
number of pages in current file
.IP %F
final overall page number
.IP %n
current filename
.IP %N
current functionname
.IP %l
login name

.SH ENVIRONMENT VARIABLES
.TP 15
.BI TP_OPTS
Specify options.  These options override any default options including
language defaults, but are overridden by command line options.
.TP 15
.BI TP_DIFF_CMD
Specify the diff command to be used.  The command must produce output
in the same format as the classic Unix diff.  This variable can be used
to add flags to the diff command used, for example to make diff ignore
whitespace.
.TP 15
.BI TP_PRINT_CMD
Specify the print command.  The default is lpr.  If this is set then it
should be set to a command that takes standard input.  If this is set
then the destination and number of copies have no effect, i.e. there is
no mechanism to pass these values to your print command.  If you set
this to /bin/cat then the postscript output will appear on stdout.
.TP 15
.BI TP_PRINTERS_FILE
Specify the printers file.  The default is the printers file that
was initially configured when trueprint was installed.  This can
be used to test out a new printers file.

.SH EXAMPLES
To print out all the C source files in the current directory:
.PP
  trueprint *.c
.PP
To print out a shell script:
.PP
  trueprint -t sh shellscript
.PP
To print all changed pages and complete changed functions, and
the function and file indexes, page 93, and pages 2 to 23, for a
changed set of files:
.PP
  trueprint -A d,D,f,F,93,2-23 -O ../OLD/ *.c
.PP
To print out a shell script showing changes:
.PP
  trueprint -t sh -O oldshell shellscript
.SH AUTHOR
Lezz Giles    giles@world.std.com
.SH SEE ALSO
.nf
.PP
diff(1)
.PP
lpr(1)
.PP
Trueprint Users' Manual
